# Generated by Django 3.0.6 on 2020-06-01 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=10)),
                ('sellers_code', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=100)),
                ('commissioners', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('responsible_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_worker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount_type', models.CharField(choices=[('PIECE', 'Piece'), ('SET', 'Set')], default='PIECE', max_length=5)),
                ('amount', models.IntegerField()),
                ('sum', models.FloatField()),
                ('reason', models.CharField(max_length=100)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='forms.Invoice')),
            ],
        ),
    ]
